//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by game.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_BITMAP1                     132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_PNG1                        159
#define IDB_BITMAP3                     166
#define IDB_PNG2                        167
#define IDB_BITMAP4                     171
#define IDB_BITMAP6                     174
#define IDB_BITMAP5                     175
#define IDB_BITMAP7                     197
#define IDB_BITMAP9                     223
#define IDB_TITLE_LOGO                  224
#define IDB_BITMAP13                    234
#define IDB_MIDGROUND5                  234
#define IDB_CHARGE                      235
#define IDB_LEFTFALL                    236
#define IDB_TITLELOGO                   237
#define IDB_RIGHTWALK3                  238
#define IDB_LEFTRISE                    239
#define IDB_LEFTSLIP                    240
#define IDB_RIGHTWALK1                  241
#define IDB_RIGHTWALK2                  242
#define IDB_RIGHTSTAND                  243
#define IDB_RIGHTSLIP                   244
#define IDB_RIGHTFALL                   245
#define IDB_RIGHTRISE                   246
#define IDB_MIDGROUND1                  247
#define IDB_LEFTWALK3                   248
#define IDB_LEFTWALK2                   249
#define IDB_LEFTWALK1                   250
#define IDB_LEFTSTAND                   251
#define IDB_MIDGROUND2                  252
#define IDB_MIDGROUND3                  253
#define IDB_MIDGROUND4                  254
#define IDB_MIDGROUND6                  256
#define IDB_MIDGROUND7                  257
#define IDB_MIDGROUND8                  258
#define IDB_MIDGROUND9                  259
#define IDB_MIDGROUND10                 260
#define IDB_MIDGROUND11                 261
#define IDB_MIDGROUND12                 262
#define IDB_MIDGROUND13                 263
#define IDB_MIDGROUND14                 264
#define IDB_MIDGROUND15                 265
#define IDB_MIDGROUND16                 266
#define IDB_MIDGROUND17                 267
#define IDB_MIDGROUND18                 268
#define IDB_MIDGROUND19                 269
#define IDB_MIDGROUND20                 270
#define IDB_MIDGROUND21                 271
#define IDB_MIDGROUND22                 272
#define IDB_MIDGROUND23                 273
#define IDB_MIDGROUND24                 274
#define IDB_MIDGROUND25                 275
#define IDB_MIDGROUND26                 276
#define IDB_MIDGROUND27                 277
#define IDB_MIDGROUND28                 278
#define IDB_MIDGROUND29                 279
#define IDB_MIDGROUND30                 280
#define IDB_MIDGROUND31                 281
#define IDB_MIDGROUND32                 282
#define IDB_MIDGROUND33                 283
#define IDB_MIDGROUND34                 284
#define IDB_MIDGROUND35                 285
#define IDB_MIDGROUND36                 286
#define IDB_MIDGROUND37                 287
#define IDB_MIDGROUND38                 288
#define IDB_MIDGROUND39                 289
#define IDB_MIDGROUND40                 290
#define IDB_MIDGROUND41                 291
#define IDB_MIDGROUND42                 292
#define IDB_MIDGROUND43                 293
#define IDB_FOREGROUND1                 294
#define IDB_FOREGROUND2                 295
#define IDB_FOREGROUND3                 296
#define IDB_FOREGROUND4                 297
#define IDB_FOREGROUND5                 298
#define IDB_FOREGROUND6                 299
#define IDB_FOREGROUND9                 300
#define IDB_FOREGROUND10                301
#define IDB_FOREGROUND16                302
#define IDB_FOREGROUND17                303
#define IDB_FOREGROUND18                304
#define IDB_FOREGROUND21                305
#define IDB_FOREGROUND22                306
#define IDB_FOREGROUND25                307
#define IDB_FOREGROUND26                308
#define IDB_FOREGROUND27                309
#define IDB_FOREGROUND28                310
#define IDB_FOREGROUND29                311
#define IDB_FOREGROUND30                312
#define IDB_FOREGROUND31                313
#define IDB_FOREGROUND32                314
#define IDB_FOREGROUND36                315
#define IDB_FOREGROUND37                316
#define IDB_FOREGROUND38                317
#define IDB_FOREGROUND39                318
#define IDB_FOREGROUND40                319
#define IDB_FOREGROUND43                320
#define IDB_BACKGROUND4                 321
#define IDB_BACKGROUND5                 322
#define IDB_BACKGROUND6                 323
#define IDB_BACKGROUND14                324
#define IDB_BACKGROUND15                325
#define IDB_BACKGROUND16                326
#define IDB_BACKGROUND17                327
#define IDB_BACKGROUND18                328
#define IDB_BACKGROUND19                329
#define IDB_BACKGROUND20                330
#define IDB_BACKGROUND21                331
#define IDB_BACKGROUND22                332
#define IDB_BACKGROUND23                333
#define IDB_BACKGROUND24                334
#define IDB_BACKGROUND25                335
#define IDB_BACKGROUND26                336
#define IDB_BACKGROUND27                337
#define IDB_BACKGROUND28                338
#define IDB_BACKGROUND29                339
#define IDB_BACKGROUND30                340
#define IDB_BACKGROUND31                341
#define IDB_BACKGROUND32                342
#define IDB_BACKGROUND36                343
#define IDB_BACKGROUND37                344
#define IDB_BACKGROUND38                345
#define IDB_BACKGROUND39                346
#define IDB_BACKGROUND40                347
#define IDB_BACKGROUND41                348
#define IDB_BACKGROUND42                349
#define IDB_BACKGROUND43                350
#define IDB_BITMAP8                     351
#define IDB_LEFTDOWN                    351
#define IDB_RIGHTDOWN                   352
#define IDB_PRESSSPACE                  353
#define IDB_PRESSSPACE_BLANK            354
#define IDB_MENUFRAME                   355
#define IDB_MENUEXTRAS                  356
#define IDB_MENUNEWGAME                 357
#define IDB_MENUOPTIONS                 358
#define IDB_BITMAP15                    359
#define IDB_MENUQUIT                    359
#define IDB_CURSOR                      361
#define IDB_PROGRESSSAVED               362
#define IDB_RECORD                      363
#define IDB_BITMAP10                    364
#define IDB_MENUCONTINUE                364
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        365
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
